### ISSUE TITLE
Noitem bug

### ISSUE THREAD

**Issue by Srextreme69** [nala3/Noitem4#1]
[23:28:21] [Server thread/ERROR]: Could not pass event InventoryClickEvent to NoItem v3.1.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-1649]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1649]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [spigot.jar:git-Spigot-1649]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-1649]
    at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1477) [spigot.jar:git-Spigot-1649]
    at net.minecraft.server.v1_7_R4.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:15) [spigot.jar:git-Spigot-1649]
    at net.minecraft.server.v1_7_R4.PacketPlayInWindowClick.handle(PacketPlayInWindowClick.java:65) [spigot.jar:git-Spigot-1649]
    at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [spigot.jar:git-Spigot-1649]
    at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1649]
    at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1649]
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1649]
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1649]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1649]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1649]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_7_R1/inventory/CraftItemStack
    at net.worldoftomorrow.noitem.events.Handlers.isCookable(Handlers.java:582) ~[?:?]
    at net.worldoftomorrow.noitem.events.Handlers.handleNoCookInvClick(Handlers.java:460) ~[?:?]
    at net.worldoftomorrow.noitem.events.Listeners.onInventoryClick(Listeners.java:69) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor191.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_65]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_65]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot.jar:git-Spigot-1649]
    ... 13 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_7_R1.inventory.CraftItemStack
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-1649]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-1649]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_65]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_65]
    at net.worldoftomorrow.noitem.events.Handlers.isCookable(Handlers.java:582) ~[?:?]
    at net.worldoftomorrow.noitem.events.Handlers.handleNoCookInvClick(Handlers.java:460) ~[?:?]
    at net.worldoftomorrow.noitem.events.Listeners.onInventoryClick(Listeners.java:69) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor191.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_65]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_65]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot.jar:git-Spigot-1649]
    ... 13 more

**Comment by just-push-it** [comment]
NoItem 3.X issue. This is the NoItem 4 Repo
